# Generated by Django 4.2 on 2025-12-01 21:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productreview_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(help_text='Процент скидки от 1 до 100', verbose_name='Процент скидки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала действия')),
                ('end_date', models.DateTimeField(blank=True, help_text='Если не указана, скидка бессрочная', null=True, verbose_name='Дата окончания действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['-created_at'],
            },
        ),
    ]
